server:
  #监听的端口号
  port: 443
  ssl:
    key-store: classpath:214472274930703.pfx
    key-store-password: 214472274930703
    key-store-type: PKCS12
    enabled: true

spring:
    http:
      multipart:
        max-file-size: 100Mb
        max-request-size: 100Mb
    datasource:
        #配置这个属性的意义在于，如果存在多个数据源，监控的时候
        #可以通过名字来区分开来。如果没有配置，将会生成一个名字，
        #格式是："DataSource-" + System.identityHashCode(this)
        name: mysql_sports_lotteries
        url: jdbc:mysql://127.0.0.1:3306/chat_analyzer?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: liuyichen
        platform: mysql
        # 初始化时建立物理连接的个数，最小连接池数量，最大连接池数量
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 获取连接时最大等待时间，单位毫秒。
        maxWait: 60000
        # testWhileIdle的判断依据，配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        #用来检测连接是否有效的sql
        validationQuery: select 1
        #此项配置为true即可，不影响性能，并且保证安全性。
        #意义为：1.申请连接的时候执行validationQuery检测连接是否有效，2.如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        testWhileIdle: true
        #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnBorrow: false
        #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小,对支持游标的数据库性能提升巨大
        #在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把maxPoolPreparedStatementPerConnectionSize配置大一些，比如说100
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 通过别名的方式配置扩展插件，配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        #常用的插件有：1.监控统计用的filter:stat 2.日志用的filter:log4j 3.防御sql注入的filter:wa
        filters: stat,wall,slf4j
        #1.通过connectProperties属性来打开mergeSql功能
        #可以自动把：
        #SELECT * FROM t FROM id = 1;
        #SELECT * FROM t FROM id = 2;
        #参数化为 select * from t where id = ?然后作为一条语句来统计。
        #2.慢sql时间设置,即执行时间大于5000毫秒的都是慢sql,将被记录下来
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    resources:
      static-locations:classpath: /static/
mybatis:
  #映射文件所在的位置   mapper文件夹下的所有xml文件
  mapper-locations: classpath:mapping/*.xml
  #对应实体所在的类
  type-aliases-package: com.EugeneStudio.ChatAnalyzer.model

#pagehelper分页插件
pagehelper:
    #使用的数据库  4.0.0以后不需要设置此属性
    helperDialect: mysql
    #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
    #禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
    #禁用合理化的时候，当请求的页数大于已有的数据量的时候 如果 数据量要求为0的时候返回所有数据
    #                                                          数据量要求大于0的时候，返回空
    #                  当请求的页数小于已有数据量的时候，所选页数就对应第几条数据
    #                                                    如果  数据量要求为0的时候返回所有数据
    #                                                          数据量要求大于0的时候，返回相应的数据
    reasonable: false
    #支持通过Mapper接口参数来传递分页参数
    supportMethodsArguments: true
    #增加了一个`params`参数来配置参数映射，用于从Map或ServletRequest中取值
    #可以配置pageNum,pageSize,count,pageSizeZero,reasonable,orderBy,不配置映射的用默认值
    params: count=countSql